### PR TITLE
stardist segmentation

### PR DESCRIPTION
**Pull request by AnnaChristina**
Open ToDos:
- [ ] document that normalize is required for stardist
- [ ] https://github.com/theislab/squidpy/issues/328
- [ ] have parameters in normalize in segment directly

### CODE REVIEW

**Comment by giovp** [comment]
was just checking out the notebooks out of curiosity, looks really promising imho!
image

**Review by hspitzer — COMMENTED** [review]
This look really impressive, great that you got it to work even for H&E stain! This looks a bit better than our watershed approach! I looks like it is still missing some cells though, is that related to the `prob_thresh` parameter?

What is the `complete_img` parameter in `stardist_3D_versatile_hne` doing? Is it not possible to just use `crop`/`img`? If you bypass the `img` parameter like this, chunking won't work properly anymore I believe? 

I'd love for this to be part of squidpy_notebooks as well (as an external tutorial - meaning it will go in docs/source/external_tutorials).

For this, some explanatory text would be good. Essentially just explaining the functions that you define, and how you are setting the parameters; similar to #11 . Also, a citation + link to the stardist code would be needed.

We can edit this here, or directly over at https://github.com/theislab/squidpy_notebooks . Have a look at the contributing guide for some hints to how the formatting should be done: https://github.com/theislab/squidpy_notebooks/blob/master/CONTRIBUTING.rst#external-tutorials

**Comment by hspitzer** [comment]
also: how did you install stardist? I've followed the hints on using `CC=gcc-10 CXX=g++-10 pip install stardist` for Mac, but no luck so far.

**Comment by giovp** [comment]
sorry just jumping on this, would be good to always make an `environemnt.yaml` file for installing the full env with conda, for reproducibility (what we have now for all external tutorials).I think a separate env per tutorial is fine?

**Comment by hspitzer** [comment]
> sorry just jumping on this, would be good to always make an `environemnt.yaml` file for installing the full env with conda, for reproducibility (what we have now for all external tutorials).I think a separate env per tutorial is fine?

that's a good point! So you would have environment_tangram.yml, environment_cellpose.yml, etc, right? And inside this, you'd always require squidpy and any other external tools that you need. And then we could just link this environment file in the tutorials.

**Comment by giovp** [comment]
Yes exactly! This would make each tutorial self contained and the user could install only a minimal env (if wants to try cell pose, no need to have tangram installed)

**Comment by AnnaChristina** [comment]
> This look really impressive, great that you got it to work even for H&E stain! This looks a bit better than our watershed approach! I looks like it is still missing some cells though, is that related to the `prob_thresh` parameter?
> 

yes, thats related to the prob_thresh parameter and I just followed their best parameter for H&E.

> What is the `complete_img` parameter in `stardist_3D_versatile_hne` doing? Is it not possible to just use `crop`/`img`? If you bypass the `img` parameter like this, chunking won't work properly anymore I believe?
> 
this was a quick fix. this is resolved now as @michalk8 allowed `channel=None` as stardist segmentation works on multiply channels. I will adjust this and remove this additional `complete_img` param. will push an update later today. 

> I'd love for this to be part of squidpy_notebooks as well (as an external tutorial - meaning it will go in docs/source/external_tutorials).
> 
will add!

> For this, some explanatory text would be good. Essentially just explaining the functions that you define, and how you are setting the parameters; similar to #11 . Also, a citation + link to the stardist code would be needed.
> 
saw this already and keep a similar structure to this matches!

> We can edit this here, or directly over at https://github.com/theislab/squidpy_notebooks . Have a look at the contributing guide for some hints to how the formatting should be done: https://github.com/theislab/squidpy_notebooks/blob/master/CONTRIBUTING.rst#external-tutorials

**Comment by AnnaChristina** [comment]
> also: how did you install stardist? I've followed the hints on using `CC=gcc-10 CXX=g++-10 pip install stardist` for Mac, but no luck so far.

I just used `pip install stardist` and it worked like a charm. I think `CC=gcc-10 CXX=g++-10 pip install stardist` is required if installation failed. I just created a new repo with only squidpy, tensorflow and stardist and it worked

**Comment by giovp** [comment]
this was merged in `squidpy_notebooks`

**Pull request closed without merging**
