### PR TITLE
external segmentation notebook (cellpose)

### PR DESCRIPTION
**Pull request by SabrinaRichter**
Got cellpose segmentation running.

Todos:
- [ ] do with proposed datasets(sq.datasets.visium_hne_image() and sq.datasets.visium_hne_adata() & sq.datasets.visium_fluo_image_crop() and sq.datasets.visium_fluo_adata_crop())
- [ ] compare results when no preprocessing, smoothing, grayscaling
- [ ] check out cellpose specific arguments
- [ ] write explanations
- [ ] change 'model' parameter in docu to 'method'

@giovp what does CI (None of these tutorials will be added to CI) mean? any comments on the todos?

### CODE REVIEW

**Comment by AnnaChristina** [comment]
hi @SabrinaRichter, just worked on my example for stardist on H&E. 

Stardist H&E model works on 3 channels, but segment method in squidpy works on only one channel (channel default is int=0)

is cellpose segmentation for H&E also working on all channels? if yes I think would make sense to allow channels=None for segmentation methods that run on all channels not just one.

@giovp also tagging you here for completeness

**Comment by giovp** [comment]
> is cellpose segmentation for H&E also working on all channels? if yes I think would make sense to allow channels=None for segmentation methods that run on all channels not just one.

@giovp also tagging you here for completeness

if you set channel = None, can you inoput the whole image to method?

**Comment by AnnaChristina** [comment]
current behaviour for `channel=None`

```
ValueError: Expected only `1` channel, found `3`.
````

**Comment by giovp** [comment]
@SabrinaRichter 

> @giovp what does CI (None of these tutorials will be added to CI) mean? 

that these notebooks will not be run on github actions continuous integration (CI) pipeline (aka tests).

re todos, all good and yes would be very valuable, not sure about this one though

> change 'model' parameter in docu to 'method'

**Comment by giovp** [comment]
> current behaviour for channel=None

ValueError: Expected only `1` channel, found `3`.

@AnnaChristina but this is with watershed? if it is with stardist, than it would be good to open the issue.

Thanks all 🙏 !

**Comment by SabrinaRichter** [comment]
> > change 'model' parameter in docu to 'method'

that is a mistake. docu says the parameter is called model, but it is method

**Comment by giovp** [comment]
ah ok! can you open issue with label docs so we remebber? thank you!

**Comment by SabrinaRichter** [comment]
does this work for you? any remarks? @giovp

**Review by hspitzer — COMMENTED** [review]
thanks for this lovely tutorial! I just tried it out and it works great. 
Did you also try this on an H&E example? Will this work or is fluo better?

With some small changes this notebook can be ported to Squidpy_notebooks, where it should be an external tutorial (meaning it will go in `docs/source/external_tutorials`). 
Could you create a PR here https://github.com/theislab/squidpy_notebooks adding this notebook? Have a look at the contributing guide for some hints to how the formatting should be done: https://github.com/theislab/squidpy_notebooks/blob/master/CONTRIBUTING.rst#external-tutorials

I'd like to ask you to add a citation + link to the cell pose repo in the header, and maybe 1 line how to install cell pose (using pip). In external tutorials we cannot use annotations like `:func:` to create links unfortunately, this will have to be done with a manual link. For the title I'd propose sth like "Nuclei segmentation using cellpose".

Thanks!

**Comment by giovp** [comment]
this was merged in `squidpy_notebooks`

**Pull request closed without merging**
