### PR TITLE
Add cellprofiler tutorial

### PR DESCRIPTION
**Pull request by LouisK92**
Compiled a tutorial for cellprofiler integration. Quite overkill for what it is. I think atm it's the best way to go with the CellProfiler GUI since there seems to be no nice documentations how to use single CellProfiler functions in a python workflow.

### CODE REVIEW

**Comment by hspitzer** [comment]
Amazing, thanks a lot! This looks really polished already. As discussed, relying on the GUI is non-optimal, but the best solution for now. The screenshots that you provide are plenty and should allow recreation of what you did. Also, for cell profiler users it will be easy.

I just executed those cells that I could and added some minor changes to enable this to run with the new z-stack changes. Would it be possible to also provide the `Squidpy_Image.csv` file so that one can look at the data without having to execute Cellprofiler? That would make things much easier for me if I decide to play around with the features a bit.

I think this is ready to go in squidpy_notebooks as an external tutorial (meaning it will go in docs/source/external_tutorials).. Could you create PR over there?  I'm not quite sure where the screenshots should go, but @michalk8 will know!

**Comment by LouisK92** [comment]
Alright👌 I uploaded the csv here. Will create a PR on squidpy_notebooks

**Comment by giovp** [comment]
@LouisK92 this can be closed cause was merged in squidpy_notebooks right?

**Comment by LouisK92** [comment]
yes

**Pull request closed without merging**
